-- 1. Criar o Tipo Enumerado para o tipo de conta
CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340; -- Ou o nome do seu usuário do banco no Render

-- 2. Criar a Tabela 'classification'
CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- 3. Criar a Tabela 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory (
	inv_id INT GENERATED BY DEFAULT AS IDENTITY,
	inv_make CHARACTER VARYING NOT NULL,
	inv_model CHARACTER VARYING NOT NULL,
	inv_year CHARACTER(4) NOT NULL,
	inv_description TEXT NOT NULL,
	inv_image CHARACTER VARYING NOT NULL,
	inv_thumbnail CHARACTER VARYING NOT NULL,
	inv_price NUMERIC(9, 0) NOT NULL,
	inv_miles INT NOT NULL,
	inv_color CHARACTER VARYING NOT NULL,
	classification_id INT NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- 4. Criar a Tabela 'account'
CREATE TABLE IF NOT EXISTS public.account (
	account_id INT GENERATED BY DEFAULT AS IDENTITY,
	account_firstname CHARACTER VARYING NOT NULL,
	account_lastname CHARACTER VARYING NOT NULL,
	account_email CHARACTER VARYING NOT NULL,
	account_password CHARACTER VARYING NOT NULL,
	account_type account_type NOT NULL DEFAULT 'Client'::account_type,
	CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- 5. Adicionar a Foreign Key (Relacionamento)
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
	REFERENCES public.classification (classification_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;

-- 6. INSERTs Iniciais (Dados da classificação)
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

-- 7. INSERTs Iniciais (Dados do inventário - Exemplos principais)
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
  )
VALUES 
  ('Chevy', 'Camaro', '2018', 'The Chevy Camaro will give you the adrenaline rush you are looking for.', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 10123, 'Silver', 2),
  ('Ford', 'Model T', '1921', 'The Ford Model T can be a bit slow but very classic.', '/images/model-t.jpg', '/images/model-t-tn.jpg', 30000, 50, 'Black', 1),
  ('GM', 'Hummer', '2016', 'Do you have 6 kids and a dog? This SUV with small interiors is for you.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58000, 20222, 'Yellow', 3),
  ('Mechanic', 'Monster Truck', '2019', 'Get the most out of your vehicle with this monster truck.', '/images/monster-truck.jpg', '/images/monster-truck-tn.jpg', 47000, 1, 'White', 1);
-- (Nota: Você pode adicionar os outros carros aqui seguindo o mesmo padrão se desejar o banco completo)

-- ==========================================================
-- TASK 1 QUERIES (ADICIONADAS AO FINAL PARA O REBUILD)
-- ==========================================================

-- Query 4: Atualizar a descrição do Hummer
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_model = 'Hummer';

-- Query 6: Atualizar caminhos das imagens para incluir /vehicles/
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');